services:
  db:
    image: postgres:15-alpine
    container_name: guardihack_pool_db
    restart: always
    environment:
      POSTGRES_USER: pool_admin
      POSTGRES_PASSWORD: super_secret_dev_password
      POSTGRES_DB: guardihack_pool_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: